(* Rocq certificates for BBrev(6) holdouts settled by mxdys CTL deciders (generated by TM FAR-branch to_coq mode).
   Check inside busycoq BB6 branch verify/ directory. *)
From BusyCoq Require Import CTL62.

Lemma nonhalt1: ~halts (TM_from_str "1RB1RF_1RC0LA_1RD---_1LE0RC_0LE1LA_0RF0RD") c0.
Proof. solve_cert (RWL_mod 1001 30000 30000 2 3200 2 3 12 0). Time Qed.

Lemma nonhalt2: ~halts (TM_from_str "1RB0LA_1RC0LE_1RD---_1LE1RF_---1LA_0RF0RC") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt3: ~halts (TM_from_str "1RB1LA_1RC0LF_1RD---_0LE0RB_0RD1LE_0LA0RC") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt4: ~halts (TM_from_str "1RB0LA_1RC1LE_1RD---_0LE1RF_0RC1LA_0RD0RF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt5: ~halts (TM_from_str "1RB0LA_1RC1LE_1RD---_0LE1RF_---1LA_0RC0RF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt6: ~halts (TM_from_str "1RB1LE_1RC1LF_1RD0RC_0LE0LF_---0LA_---1LA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt7: ~halts (TM_from_str "1RB1LE_1RC0RC_1RD0LE_0LA0RD_0LF1LF_---1LA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt8: ~halts (TM_from_str "1RB0LF_1RC0RB_1LD0RE_1LF1RE_---1LA_0LA0RC") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt9: ~halts (TM_from_str "1RB1LF_1RC0RA_1LD0RC_0RB1LE_0LD0LF_0LE---") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt10: ~halts (TM_from_str "1RB0RC_1RC---_1LD0RA_0RF1LE_0LD0LE_1RF1RA") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 2 4 2 0). Time Qed.

Lemma nonhalt11: ~halts (TM_from_str "1RB1LF_1RC1RA_1LD0RC_0LF1LE_---0LD_0RA0LE") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt12: ~halts (TM_from_str "1RB0LD_1RC0LE_1LD1RF_1LA1LE_---0LA_0RC0RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt13: ~halts (TM_from_str "1RB1LF_1RC1RE_1LD0RB_1LA0RE_---0RC_0LA0LF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt14: ~halts (TM_from_str "1RB0RC_1RC1LE_1LD0RA_1RA0LE_---1LF_0LD0LF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt15: ~halts (TM_from_str "1RB0RA_1RC---_1LD---_0LE0LD_0RF1RA_1RF1LE") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 1 3 2 0). Time Qed.

Lemma nonhalt16: ~halts (TM_from_str "1RB1LE_1RC---_1LD---_0LE0LD_0RF1RA_1RF0RA") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 1 3 2 0). Time Qed.

Lemma nonhalt17: ~halts (TM_from_str "1RB0RA_1RC1LE_1LD---_1RF0RB_0LE0LD_0RF1RA") c0.
Proof. solve_cert (RWL_mod_FAR 200000 100000 1 3200 1 3 1 0). Time Qed.

Lemma nonhalt18: ~halts (TM_from_str "1RB---_1RC0RC_1LD1RA_0LE0RB_0RA1LF_0LD0LF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt19: ~halts (TM_from_str "1RB0LA_1RC1RF_0RD---_1LE1LA_0LE1RD_0RF0RC") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt20: ~halts (TM_from_str "1RB1LF_1RC0RB_0RD0LA_1LE0RC_1LA---_0LF0LE") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt21: ~halts (TM_from_str "1RB0LF_1RC1LF_0RD0LA_1LE0RC_1LA0LE_---1RD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt22: ~halts (TM_from_str "1RB1RE_1RC1RD_0RD0RC_0RE---_0LF0LA_1LF1LA") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt23: ~halts (TM_from_str "1RB0LA_1RC1RF_0RD---_0LE1LA_1LE1RD_0RC0RF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt24: ~halts (TM_from_str "1RB0LA_1RC---_0RD1RD_0LE1RF_1LE1LA_0RC0RF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt25: ~halts (TM_from_str "1RB1LF_1RC---_0RD0RC_0LE0RB_1LE0LA_1RD0LF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt26: ~halts (TM_from_str "1RB1RD_1RC1RF_0RD---_0LE1LA_1LE0LA_0RC0RF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt27: ~halts (TM_from_str "1RB1LF_1RC1RD_0RD---_0LE0RB_0LA0RC_1LA0LF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt28: ~halts (TM_from_str "1RB1LE_1RC0LE_0RD0RC_1LA0LF_---0LA_1LF1RD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt29: ~halts (TM_from_str "1RB1RD_1RC0LE_0RD0RC_1LA0LF_---0LA_1LF1LE") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt30: ~halts (TM_from_str "1RB0LF_1RC0RB_0LD0RE_1LF1RE_1LA---_0LA0RC") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt31: ~halts (TM_from_str "1RB0LA_1RC1LD_0LD0RF_0RB1LE_1LA1RF_---0RC") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt32: ~halts (TM_from_str "1RB0LA_1RC1LD_0LD0RF_0RC1LE_1LA1RF_---0RB") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt33: ~halts (TM_from_str "1RB0RA_1RC0LE_0LD1RA_---1LE_0LF1LF_0RB1LD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt34: ~halts (TM_from_str "1RB---_1RC1LD_0LD0RC_0RB1LE_1LA1LF_0LA0LF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt35: ~halts (TM_from_str "1RB---_1RC1LD_0LD0RB_0RC1LE_1LA1LF_0LA0LF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt36: ~halts (TM_from_str "1RB0RA_1RC---_0LD0RC_1RA1LE_1LD0LF_0RB0LE") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt37: ~halts (TM_from_str "1RB---_1RC1RF_0LD0RB_1LD1LE_1LA0LE_0RC0RF") c0.
Proof. solve_cert (RWL_mod 0 30000 30000 2 3200 2 1 4 0). Time Qed.

Lemma nonhalt38: ~halts (TM_from_str "1RB1LD_1RC0RB_0LD1RF_---1LE_0LE0LA_1LA0RF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt39: ~halts (TM_from_str "1RB0LE_1RC---_0LD0RF_0RC1LE_1RF0LA_0RB1LD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt40: ~halts (TM_from_str "1RB0LE_1RC---_0LD0RC_0RF1LE_1RF0LA_0RB1LD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt41: ~halts (TM_from_str "1RB---_1RC0RC_0LD0RB_0LF1LE_1LD0LA_1LF0LE") c0.
Proof. solve_cert (NG 0 2000 2000 2 0 0 0 false). Time Qed.

Lemma nonhalt42: ~halts (TM_from_str "1RB0LE_1RC---_0LD0RF_1LE1LD_0LA1RF_0RB0RC") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt43: ~halts (TM_from_str "1RB0LE_1RC---_0LD1LE_0RC1LD_0LA0RF_0RB1RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt44: ~halts (TM_from_str "1RB0LE_1RC---_0LD0RA_0RC1LD_0LF0RB_1RA1LF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt45: ~halts (TM_from_str "1RB0RC_1RC---_0LD1LE_1RA1LD_0LF0RA_0RB0LE") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt46: ~halts (TM_from_str "1RB0LE_1RC---_0LD1RA_0RA1LD_0LF0RB_0RC1LF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt47: ~halts (TM_from_str "1RB0LE_1RC---_0LD1LE_0LA1LD_0RC0RF_0RB1RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt48: ~halts (TM_from_str "1RB0LE_1RC---_0LD1LE_1LD0RC_0LA1RF_0RB0RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt49: ~halts (TM_from_str "1RB1LE_1RC1LD_0LD0RF_0RB1LA_0LA0LE_---0RC") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt50: ~halts (TM_from_str "1RB1LE_1RC1LD_0LD0RF_0RC1LA_0LA0LE_---0RB") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt51: ~halts (TM_from_str "1RB1LD_1RC0RB_1LA1RF_0RF1LE_0LA0RC_---0LE") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt52: ~halts (TM_from_str "1RB1LD_1RC1RE_1LA0RC_0LF0LA_0RB1LF_---0LD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt53: ~halts (TM_from_str "1RB1LD_1RC0RE_1LA0RC_0LF0LA_0RB1LF_0LD---") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt54: ~halts (TM_from_str "1RB0LD_1RC0RB_1LA1RF_0RF1LE_0LA0RC_0LE---") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt55: ~halts (TM_from_str "1RB0LD_1RC0RB_1LA0RF_1LD1LE_0LA---_0RC0LE") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt56: ~halts (TM_from_str "1RB0LD_1RC1LE_1LA1RF_0LA0RC_0RF1LD_---0RB") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt57: ~halts (TM_from_str "1RB0LD_1RC0LE_1LA1RF_0LA0RC_0RF1LD_0RB---") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt58: ~halts (TM_from_str "1RB1LD_1RC0RB_0LA0RC_1LE0LD_1LF---_1LA---") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt59: ~halts (TM_from_str "1RB1LD_1RC---_0LA1RF_1LE0LD_0RC0LE_0RF0RB") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt60: ~halts (TM_from_str "1RB1LD_1RC0RB_0LA0RC_1LE0LD_1LA---") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt61: ~halts (TM_from_str "1RB1LD_1RC1RE_0LA0RC_0LF1LA_0RB1LF_---0LD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt62: ~halts (TM_from_str "1RB1LD_1RC0RE_0LA0RC_0LF1LA_0RB1LF_0LD---") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt63: ~halts (TM_from_str "1RB0LD_1RC1RF_0LA0RF_0RB1LE_1LD1LA_---0RC") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt64: ~halts (TM_from_str "1RB0LD_1RC0RF_0LA1RF_0RC1LE_1LA1LD_---0RB") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt65: ~halts (TM_from_str "1RB0LD_1RC1RE_0LA0LF_---1LA_0RC0RE_1LF1LD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt66: ~halts (TM_from_str "1RB0LD_1RC1RE_0LA0LF_---1LA_0RC1LF_0RE1LD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt67: ~halts (TM_from_str "1RB1LF_1LC0RE_1LA1RD_0LF1RE_0RB0LA_---0LC") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt68: ~halts (TM_from_str "1RB0RA_1LC0RD_1LF1RD_---1LE_1RA0LF_0LE0RB") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt69: ~halts (TM_from_str "1RB---_1LC---_0LA1RD_0RD0RE_0RB1LF_0LF0LC") c0.
Proof. solve_cert (CPS_LRU 1001 100000 100000 2 3200 1 14 1 0). Time Qed.

Lemma nonhalt70: ~halts (TM_from_str "1RB0LF_1LC---_0LA1RD_1RE0RD_0RB0RE_0LC1LF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt71: ~halts (TM_from_str "1RB1LA_1LC0LF_0LA1RD_1RE0RD_0RB---_0RE0LC") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt72: ~halts (TM_from_str "1RB0LF_1LC0RB_0LA1RD_0RE0RD_1LA---_0LC1RE") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt73: ~halts (TM_from_str "1RB0LA_1LC1RF_1LE1RD_---0RB_0LE1LA_0RF0RD") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt74: ~halts (TM_from_str "1RB0LA_1LC1RF_1LE1RD_0RF0RB_0LC1LA_---0RD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt75: ~halts (TM_from_str "1RB0LA_1LC1RF_1LE1RD_0RD0RB_0RF1LA_---0LC") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt76: ~halts (TM_from_str "1RB0LA_1LC1RF_0LE1RD_---0RB_1LE1LA_0RD0RF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt77: ~halts (TM_from_str "1RB0LA_1LC1RF_0LE1RD_0RF0RB_0LC1LA_0RD---") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt78: ~halts (TM_from_str "1RB0LA_1LC1RF_0LE1RD_0RD0RB_0RF1LA_0LC---") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt79: ~halts (TM_from_str "1RB0LA_1LC1RF_0LC1RD_1LE0RB_0RF1LA_---0RD") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt80: ~halts (TM_from_str "1RB0LA_1LC1RF_0LC1RD_0LE0RB_0RF1LA_0RD---") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt81: ~halts (TM_from_str "1RB0LD_1LC---_0LC1LD_1RE0LA_0RB1RF_0RF0RE") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt82: ~halts (TM_from_str "1RB0LA_1LC0RE_0LC1LD_1RE1LA_---1RF_0RF0RB") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt83: ~halts (TM_from_str "1RB0RA_1LC---_0RE1LD_1RE0LC_0LD0RF_0RB1RA") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt84: ~halts (TM_from_str "1RB0RA_1LC1RA_1LF1LD_1RE0LC_0RB0LF_---0LD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt85: ~halts (TM_from_str "1RB0RA_1LC1RA_0RE1LD_1RE0LF_0LD0RB_0LC---") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt86: ~halts (TM_from_str "1LB---_1RC0RE_0RC1RD_1RE0RD_1LF---_0LF0LB") c0.
Proof. solve_cert (RWL_mod_FAR 200000 100000 1 3200 2 4 1 0). Time Qed.

Lemma nonhalt87: ~halts (TM_from_str "1RB0LD_1LC0RF_1RF1LD_1LE---_0LC0LE_0RB0RA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt88: ~halts (TM_from_str "1RB0LD_1LC0RB_0RF1LD_1LE---_0LC0LE_1RF0RA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt89: ~halts (TM_from_str "1LB---_1RC0RE_0RC1RD_1RE0RD_1RA1LF_0LF0LB") c0.
Proof. solve_cert (RWL_mod_FAR 200000 100000 1 3200 2 6 1 0). Time Qed.

Lemma nonhalt90: ~halts (TM_from_str "1RB0RA_1LC---_1RE1LD_0RE0LD_0LC1RF_0RB1RA") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt91: ~halts (TM_from_str "1RB0RA_1LC1RA_1LF1LD_0RE0LC_0RB0LF_0LD---") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt92: ~halts (TM_from_str "1RB0RA_1LC1RE_1RA1LD_0RE1LF_---0LF_0LC0RB") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt93: ~halts (TM_from_str "1RB0LD_1LC1RF_0LC1LD_0RE0LA_---1LA_0RF0RB") c0.
Proof. solve_cert (RWL_mod 0 30000 30000 2 3200 2 1 4 0). Time Qed.

Lemma nonhalt94: ~halts (TM_from_str "1RB0RA_1LC---_---1LD_0LE0LD_0RF0LC_1RF1RA") c0.
Proof. solve_cert (RWL_mod 0 30000 30000 2 3200 2 1 4 0). Time Qed.

Lemma nonhalt95: ~halts (TM_from_str "1RB0LD_1LC0RB_0RF1LD_0LE---_0LC1LE_0RA1RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt96: ~halts (TM_from_str "1RB---_1LC0RF_0RE1LD_0LC0LD_1RE1RF_1RA0RB") c0.
Proof. solve_cert (CPS_LRU 0 10000 10000 4 3200 0 3 1 0). Time Qed.

Lemma nonhalt97: ~halts (TM_from_str "1RB0RB_1LC0RA_0RE1LD_0LC0LD_1RE0LF_---1RA") c0.
Proof. solve_cert (RWL_mod 0 30000 30000 2 3200 2 1 4 0). Time Qed.

Lemma nonhalt98: ~halts (TM_from_str "1RB1RF_1LC---_0RE1LD_0LC0LD_1RE1RA_0RB0RF") c0.
Proof. solve_cert (CPS_LRU 1001 100000 100000 2 3200 1 14 1 0). Time Qed.

Lemma nonhalt99: ~halts (TM_from_str "1RB0LF_1LC---_0RE1LD_0LC0LD_1RE1RA_---0RB") c0.
Proof. solve_cert (RWL_mod 0 30000 30000 2 3200 2 1 4 0). Time Qed.

Lemma nonhalt100: ~halts (TM_from_str "1RB0RB_1LC1LF_0RE1LD_0LC0LD_1RE1RA_0RA---") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 2 6 2 0). Time Qed.

Lemma nonhalt101: ~halts (TM_from_str "1RB0LA_1LC1RE_1LA1LD_0LC1RF_0RF0RB_---0RE") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt102: ~halts (TM_from_str "1RB1RE_1LC0RB_0RA1LD_0LC0LF_1RA1LF_---0LD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt103: ~halts (TM_from_str "1RB0RE_1LC0RB_0RA1LD_0LC0LF_1RA1LF_0LD---") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt104: ~halts (TM_from_str "1RB0LC_1LC1RE_0LA1LD_1LA0RE_---1RF_0RB0RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt105: ~halts (TM_from_str "1RB0LA_1LC1RE_0LC1LD_1LA0RE_---1RF_0RF0RB") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt106: ~halts (TM_from_str "1RB0LC_1LC0RE_0LA1LD_1LA1RE_---1RF_0RB0RF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt107: ~halts (TM_from_str "1RB0LA_1LC0RE_0LC1LD_1LA1RE_---1RF_0RF0RB") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt108: ~halts (TM_from_str "1RB1LF_1LC0RE_1LA0RD_0LF1RE_0RB0LA_0LC---") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt109: ~halts (TM_from_str "1RB1RD_1LC0RA_1LE0RD_---0RB_1RA1LF_0LE0LF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt110: ~halts (TM_from_str "1RB0RF_1LC1RD_1LE0RD_---0RB_0LA0LE_1RF1LA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt111: ~halts (TM_from_str "1RB0RF_1LC1LA_1LE0RD_---0RB_0LA0LE_1RF1RD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt112: ~halts (TM_from_str "1RB0LA_1LC0RE_0LC0LD_1RE1LA_1RF---_0RF0RB") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt113: ~halts (TM_from_str "1RB0RA_1LC---_0LC0LD_1RE0RB_0RF---_0RE1RA") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt114: ~halts (TM_from_str "1RB0RA_1LC1RA_0LF0LD_1RE0RB_0RE1LD_0LC---") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt115: ~halts (TM_from_str "1RB0RA_1LC---_0LC0LD_1RE0RB_0RE1RA") c0.
Proof. solve_cert (RWL_mod_FAR 200000 100000 1 3200 1 2 1 0). Time Qed.

Lemma nonhalt116: ~halts (TM_from_str "1RB1LD_1LC0RF_1RF0LD_1LE---_0LC0LE_0RB0RA") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt117: ~halts (TM_from_str "1RB1LD_1LC0RF_1RF0LD_1LE---_0LC0LE_0RA0RB") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt118: ~halts (TM_from_str "1RB1LD_1LC0RB_0RF0LD_1LE---_0LC0LE_1RF0RA") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt119: ~halts (TM_from_str "1RB1RA_1LC0RF_0RA0LD_1LE1LD_0LC---_0RB0LE") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt120: ~halts (TM_from_str "1RB0RA_1LC1RE_1RA0LD_0RE1LF_0LF---_0LC0RB") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt121: ~halts (TM_from_str "1RB---_1LC0RB_1RF0LD_0LE1LD_0LC1RA_0RA0RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt122: ~halts (TM_from_str "1RB1LE_1LC1RF_1RA0LD_0LC0RB_0RF1LD_---0RA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt123: ~halts (TM_from_str "1RB0LE_1LC1RF_1RA0LD_0LC0RB_0RF1LD_0RA---") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt124: ~halts (TM_from_str "1RB0LA_1LC1RE_1LA0LD_0LC1RF_0RF0RB_0RE---") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt125: ~halts (TM_from_str "1RB0LC_1LC1RE_0LA0LD_1LA0RE_1RF---_0RB0RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt126: ~halts (TM_from_str "1RB0LA_1LC1RE_0LC0LD_1LA0RE_1RF---_0RF0RB") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt127: ~halts (TM_from_str "1LB---_1RC1LE_0RC0RD_1RA1RF_0LE0LB_0RA0RF") c0.
Proof. solve_cert (RWL_mod_FAR 200000 100000 1 3200 2 4 1 0). Time Qed.

Lemma nonhalt128: ~halts (TM_from_str "1RB0LC_1LC0RE_0LA0LD_1LA1RE_1RF---_0RB0RF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt129: ~halts (TM_from_str "1RB0LA_1LC0RE_0LC0LD_1LA1RE_1RF---_0RF0RB") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt130: ~halts (TM_from_str "1RB---_1LC0RD_1RD0LC_1LE1RA_0RB0LF_0LE0RA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt131: ~halts (TM_from_str "1RB---_1LC0RB_1RD0LC_1LE1RF_0RA0LE_1RA---") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt132: ~halts (TM_from_str "1RB---_1LC0RB_1RD0LC_1LE1RA_0RA0LE") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt133: ~halts (TM_from_str "1RB---_1LC0RE_1RD0LC_0RB1LF_0RD1LA_0LA0LF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt134: ~halts (TM_from_str "1RB0LA_1LC1RE_1LD0LC_0RE1LA_---1RF_0RF0RB") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt135: ~halts (TM_from_str "1RB---_1LC0RF_1LD0LC_0RE0LA_1RF1LA_0RB0LD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt136: ~halts (TM_from_str "1RB0RE_1LC---_1LD0LC_1RA0LF_1RE0RA_0LD0RB") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt137: ~halts (TM_from_str "1RB0LA_1LC1RE_0LD0LC_0RE1LA_1RF---_0RF0RB") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt138: ~halts (TM_from_str "1RB0RA_1LC---_0LD0LC_0RE1RA_1RF1LD_1RE---") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt139: ~halts (TM_from_str "1RB1LD_1LC---_0LD0LC_0RE1RA_1RF0RA_1RE---") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt140: ~halts (TM_from_str "1RB---_1LC---_0LD0LC_0RE1RA_1RE1RF_0RA0RF") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 1 3 2 0). Time Qed.

Lemma nonhalt141: ~halts (TM_from_str "1RB0RF_1LC---_0LD0LC_0RE1RA_1RE1RF_0RA1LD") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 1 3 2 0). Time Qed.

Lemma nonhalt142: ~halts (TM_from_str "1RB---_1LC---_0LD0LC_0RE1RF_1RE0RF_1RA1LD") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 1 3 2 0). Time Qed.

Lemma nonhalt143: ~halts (TM_from_str "1RB---_1LC---_0LD0LC_0RE1RF_1RE1LD_1RA0RF") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 1 3 2 0). Time Qed.

Lemma nonhalt144: ~halts (TM_from_str "1RB1RF_1LC---_0LD0LC_0RE1RA_1RE1LD_0RA0RF") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 1 3 2 0). Time Qed.

Lemma nonhalt145: ~halts (TM_from_str "1RB0RA_1LC---_0LD0LC_0RE1RA_1RE1LD") c0.
Proof. solve_cert (CPS_LRU 1001 100000 100000 2 3200 1 14 1 0). Time Qed.

Lemma nonhalt146: ~halts (TM_from_str "1RB1LF_1LC0RA_0LD0LC_0RE1RA_1RE0RB_1LD---") c0.
Proof. solve_cert (RWL_mod 1001 300000 300000 2 3200 1 5 4 0). Time Qed.

Lemma nonhalt147: ~halts (TM_from_str "1RB1LF_1LC1LD_0LD0LC_0RE1RA_1RE0RA_0RB---") c0.
Proof. solve_cert (CPS_LRU 1001 100000 100000 2 3200 1 14 1 0). Time Qed.

Lemma nonhalt148: ~halts (TM_from_str "1RB1LD_1LC---_0LD0LC_0RE1RA_1RE0RA") c0.
Proof. solve_cert (CPS_LRU 1001 100000 100000 2 3200 1 14 1 0). Time Qed.

Lemma nonhalt149: ~halts (TM_from_str "1RB0LA_1LC0RE_0LD0LC_1LA---_0RF1RE_0RB1LD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt150: ~halts (TM_from_str "1RB0RA_1LC0LD_0RB0LC_0LE---_0RF1RA_1RF1LE") c0.
Proof. solve_cert (CPS_LRU 1001 100000 100000 2 3200 1 14 1 0). Time Qed.

Lemma nonhalt151: ~halts (TM_from_str "1RB1LE_1LC0LD_0RB0LC_0LE---_0RF1RA_1RF0RA") c0.
Proof. solve_cert (CPS_LRU 1001 100000 100000 2 3200 1 14 1 0). Time Qed.

Lemma nonhalt152: ~halts (TM_from_str "1RB1LD_1LC0RA_0RB0LC_0LE0LD_0RF---_1RF1RA") c0.
Proof. solve_cert (RWL_mod 0 30000 30000 2 3200 2 1 4 0). Time Qed.

Lemma nonhalt153: ~halts (TM_from_str "1RB0LD_1LC0RA_0RB0LC_1LE1LD_0RF---_1RA1RF") c0.
Proof. solve_cert (RWL_mod 0 30000 30000 2 3200 2 1 4 0). Time Qed.

Lemma nonhalt154: ~halts (TM_from_str "1RB1LE_1LC1RD_1LA0LC_0LE1RF_---0RF_0RB0LA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt155: ~halts (TM_from_str "1RB1LE_1LC0RD_1LA0LC_0LE1RF_0RF---_0RB0LA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt156: ~halts (TM_from_str "1RB0LF_1LC0RD_1LA0LC_1RD1RE_0RB---_0LA0RE") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt157: ~halts (TM_from_str "1RB1LD_1LC---_0RE1RA_0LC0LD_1RE1RF_0RA0RF") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 1 3 2 0). Time Qed.

Lemma nonhalt158: ~halts (TM_from_str "1RB0LF_1LC1RD_0LC1LA_0RD0RE_0RB---_1RE0LA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt159: ~halts (TM_from_str "1RB0LF_1LC1RD_0LC1LA_0RD0RE_0RB---_0LA1RE") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt160: ~halts (TM_from_str "1RB0LF_1LC1RD_---1LA_---0RE_0LA1RE_0RD1LF") c0.
Proof. solve_cert (CPS_LRU 1001 100000 100000 2 3200 1 14 1 0). Time Qed.

Lemma nonhalt161: ~halts (TM_from_str "1RB1LF_1LC1RD_---1LA_1RE0RD_0LA0RE_0LF0LC") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt162: ~halts (TM_from_str "1RB0LA_1LC1RD_1LE1LA_0RF0RB_0LC1RF_---0RD") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt163: ~halts (TM_from_str "1RB0LA_1LC1RD_0LE1LA_0RF0RB_0LC1RF_0RD---") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt164: ~halts (TM_from_str "1RB1LF_1LC0RD_---1LA_1RE1RD_0LA0RE_0LC0LF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt165: ~halts (TM_from_str "1RB1RF_1LC0RB_1LD1LA_1RE0LA_0LD0RE_---0LC") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt166: ~halts (TM_from_str "1RB1LD_1LC---_---0RA_0LE0LD_0RF0LC_1RF1RA") c0.
Proof. solve_cert (CPS_LRU 1001 100000 100000 2 3200 1 14 1 0). Time Qed.

Lemma nonhalt167: ~halts (TM_from_str "1RB0LF_0RC1LE_1RD---_0LE0RD_0RB1LA_1RC0LA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt168: ~halts (TM_from_str "1RB0LF_0RC1LE_1RD---_0LE0RB_0RD1LA_1RC0LA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt169: ~halts (TM_from_str "1RB1LE_0RC0RB_1RD0LE_1LA0RD_0LF---_1LF0LA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt170: ~halts (TM_from_str "1RB0LE_0RC0RB_1RD---_1LA0RD_0LF1LE_0LA1RC") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt171: ~halts (TM_from_str "1RB1LE_0RC1RC_1RD0LE_0LA0RD_1LF0LF_---1LA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt172: ~halts (TM_from_str "1RB1RA_0RC0LE_1LD0RB_1LE---_0RA1LF_0LD0LF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt173: ~halts (TM_from_str "1RB1LF_0RC0LE_1LD0RB_1LE0LD_0RA0LF_1RC---") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt174: ~halts (TM_from_str "1RB0LD_0RC0LE_1LD1RF_1LE1LA_---0LA_1RC0RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt175: ~halts (TM_from_str "1RB1LE_0RC0LF_1LD0RB_0LE---_0RA1LF_0LD1RA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt176: ~halts (TM_from_str "1RB0RA_0RC0RB_1LD---_0LE1RA_1RC0LF_0LD1LF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt177: ~halts (TM_from_str "1RB0RA_0RC---_1LD0LF_0LE1RA_1RC1LE_0RB0LD") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt178: ~halts (TM_from_str "1RB1LF_0RC0LF_1LD0RB_0LE---_0RA1LE_0LD1RA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt179: ~halts (TM_from_str "1RB---_0RC0RB_1LD1RA_0LE0LF_1RC0LD_1LE0RA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt180: ~halts (TM_from_str "1RB---_0RC0RB_1LD0RA_0LE0LF_1RC0LD_1LE1RA") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt181: ~halts (TM_from_str "1RB0RB_0RC0RA_1LD---_0LE0LD_0RF1RC_1RF1RA") c0.
Proof. solve_cert (RWL_mod 1001 300000 300000 2 3200 1 5 4 0). Time Qed.

Lemma nonhalt182: ~halts (TM_from_str "1RB0RA_0RC1RC_1LD---_0LE0LD_0RF1RA_1RF1LE") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 2 4 3 0). Time Qed.

Lemma nonhalt183: ~halts (TM_from_str "1RB1LE_0RC1RC_1LD---_0LE0LD_0RF1RA_1RF0RA") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 2 4 3 0). Time Qed.

Lemma nonhalt184: ~halts (TM_from_str "1RB0LE_0RC---_1LD1RF_0LD1LE_1RC0LA_0RF0RB") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt185: ~halts (TM_from_str "1RB---_0RC1RF_1LD1LA_0LD1LE_0LA0LE_0RF0RB") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt186: ~halts (TM_from_str "1RB0RA_0RC1RA_1LD---_0LD0LE_1RF0RB_0RF1LE") c0.
Proof. solve_cert (RWL_mod_FAR 200000 100000 1 3200 1 3 1 0). Time Qed.

Lemma nonhalt187: ~halts (TM_from_str "1RB0RA_0RC---_1LD---_0LD0LE_1RF0RB_0RF1RA") c0.
Proof. solve_cert (RWL_mod_FAR 200000 100000 1 3200 1 3 1 0). Time Qed.

Lemma nonhalt188: ~halts (TM_from_str "1RB0LA_0RC1RE_1LD1LF_0LD1LA_0RE0LF_0RB---") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt189: ~halts (TM_from_str "1RB0LF_0RC1RE_1LD---_0LD1LA_0RE0RB_1RC0LA") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt190: ~halts (TM_from_str "1RB0LF_0RC1RE_1LD---_0LD1LA_0RE0RB_0LA1RC") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt191: ~halts (TM_from_str "1RB0LF_0RC0RE_1LD---_0LD1LA_1RE0RB_0LA1RC") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt192: ~halts (TM_from_str "1RB1RD_0RC0RB_0RD---_0LE1LA_1LE0LF_1RC0LA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt193: ~halts (TM_from_str "1RB0LF_0RC0RB_0RD---_0LE1LA_1LE1RD_1RC0LA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt194: ~halts (TM_from_str "1RB0LF_0RC0RB_0RD1LA_0LE---_1LE0LA_1RD1RC") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt195: ~halts (TM_from_str "1RB0LF_0RC0RB_0RD1LA_0LE---_1LE0LA_1RC1RD") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt196: ~halts (TM_from_str "1RB0LA_0RC1LD_0LD1RF_1RE1LA_1RC---_0RE0RF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt197: ~halts (TM_from_str "1RB0LA_0RC0RF_0LD1LA_1LE1RC_1LD1RF_---0RB") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt198: ~halts (TM_from_str "1RB1RC_0RC0RF_0LD1LA_1LE0LA_1LD1RF_---0RB") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt199: ~halts (TM_from_str "1RB0RA_0RC0LE_0LD1RA_1LE---_0LF1LF_0RB1LD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt200: ~halts (TM_from_str "1RB---_0RC0RB_0LD1LA_1LE---_1LD1LF_0LA0LF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt201: ~halts (TM_from_str "1RB1LD_0RC0RB_0LD1LA_1LE---_1RC1LF_0LA0LF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt202: ~halts (TM_from_str "1RB0LE_0RC---_0LD1RF_1LE1RC_0LA0RF_0RB1LD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt203: ~halts (TM_from_str "1RB0LE_0RC---_0LD1RC_1LE1RF_0LA0RF_0RB1LD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt204: ~halts (TM_from_str "1RB1RA_0RC---_0LD0RA_1LE1LD_1RC0LF_0LE0RB") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt205: ~halts (TM_from_str "1RB0LA_0RC1RF_0LD0RF_1LE1RC_1LA1LD_---0RB") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt206: ~halts (TM_from_str "1RB1LF_0RC0RB_0LD1LA_1LE---_1LD1RC_0LA0LF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt207: ~halts (TM_from_str "1RB1LD_0RC---_0LD1RA_1LE0LF_1RC0RA_0RB0LE") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt208: ~halts (TM_from_str "1RB1LD_0RC0RB_0LD1RF_1LE---_0LE0LA_1LA0RF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt209: ~halts (TM_from_str "1RB1RC_0RC---_0LD0RA_0LE0RB_1RA1LF_1LE0LF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt210: ~halts (TM_from_str "1RB---_0RC0RB_0LD1RA_0LE1LD_0RA1LF_1RC0LF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt211: ~halts (TM_from_str "1RB---_0RC0RB_0LD1LA_1LD1LE_1LF0LF_0LA0LE") c0.
Proof. solve_cert (RWL_mod 1001 300000 300000 2 3200 1 5 4 0). Time Qed.

Lemma nonhalt212: ~halts (TM_from_str "1RB---_0RC0RB_0LD1LF_1LD1LE_0LF0LE_1LA---") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 1 3 2 0). Time Qed.

Lemma nonhalt213: ~halts (TM_from_str "1RB---_0RC0RB_0LD1LF_1LD1LE_0LF1RC_1LA0LE") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 1 3 2 0). Time Qed.

Lemma nonhalt214: ~halts (TM_from_str "1RB0LE_0RC---_0LD1RF_1LD1LE_1RC0LA_0RB0RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt215: ~halts (TM_from_str "1RB---_0RC1RF_0LD1LA_1LD1LE_0LA0LE_0RB0RF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt216: ~halts (TM_from_str "1RB---_0RC0RF_0LD1LA_1LD1LE_0LA0LE_---0RB") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt217: ~halts (TM_from_str "1RB---_0RC0RB_0LD1LA_1LD1LE_0LA1LF_0LE0LF") c0.
Proof. solve_cert (RWL_mod 1001 300000 300000 2 3200 1 5 4 0). Time Qed.

Lemma nonhalt218: ~halts (TM_from_str "1RB---_0RC0RB_0LD1LA_1LD1LE_0LA0LE") c0.
Proof. solve_cert (CPS_LRU 1001 100000 100000 2 3200 1 14 1 0). Time Qed.

Lemma nonhalt219: ~halts (TM_from_str "1RB1RC_0RC1LE_0LD---_1LD0LE_1RF0LA_0RB0RF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt220: ~halts (TM_from_str "1RB---_0RC0RB_0LD1RA_1LD0LE_1LF0RA_1RC0LF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt221: ~halts (TM_from_str "1RB---_0RC0RB_0LD0RA_1LD0LE_1LF1RA_1RC0LF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt222: ~halts (TM_from_str "1RB---_0RC0RB_0LD1LE_1LD0LE_1LF1RC_1LA---") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 1 3 2 0). Time Qed.

Lemma nonhalt223: ~halts (TM_from_str "1RB---_0RC0RB_0LD1LE_1LD0LE_1LF1RC_0LA1LA") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 2 4 3 0). Time Qed.

Lemma nonhalt224: ~halts (TM_from_str "1RB---_0RC0RB_0LD0RA_1LD0LE_1RA1LF_1RC0LF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt225: ~halts (TM_from_str "1RB1RC_0RC0RB_0LD1LE_1LD0LE_1LA1RF_0LA---") c0.
Proof. solve_cert (CPS_LRU 1001 100000 100000 2 3200 1 14 1 0). Time Qed.

Lemma nonhalt226: ~halts (TM_from_str "1RB---_0RC0RB_0LD1LE_1LD0LE_1LA1RC") c0.
Proof. solve_cert (CPS_LRU 1001 100000 100000 2 3200 1 14 1 0). Time Qed.

Lemma nonhalt227: ~halts (TM_from_str "1RB---_0RC0RB_0LD1LE_1LD1RC_1LA1LF_0LE0LF") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 1 3 2 0). Time Qed.

Lemma nonhalt228: ~halts (TM_from_str "1RB---_0RC0RB_0LD1LE_1LD1RC_1LF0LE_1LA---") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 1 3 2 0). Time Qed.

Lemma nonhalt229: ~halts (TM_from_str "1RB---_0RC0RB_0LD1LE_1LD1RC_1LF0LE_0LA1LA") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 2 4 3 0). Time Qed.

Lemma nonhalt230: ~halts (TM_from_str "1RB---_0RC0RB_0LD1LE_1LD1RC_1LA0LE") c0.
Proof. solve_cert (CPS_LRU 1001 100000 100000 2 3200 1 14 1 0). Time Qed.

Lemma nonhalt231: ~halts (TM_from_str "1RB0LE_0RC---_0LD1LE_1LD1RC_1RF0LA_0RB0RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt232: ~halts (TM_from_str "1RB1LE_0RC0RF_0LD1LA_1LD1RC_0LA0LE_---0RB") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt233: ~halts (TM_from_str "1RB0LF_0RC1RE_0LD---_1LD1LA_0RB0RE_1RC0LA") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt234: ~halts (TM_from_str "1RB0LF_0RC1RE_0LD---_1LD1LA_0RB0RE_0LA1RC") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt235: ~halts (TM_from_str "1RB0LF_0RC0RE_0LD---_1LD1LA_0RB1RE_0LA1RC") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt236: ~halts (TM_from_str "1RB0LE_0RC---_0LD1LE_1LD0LA_1RF1RC_0RB0RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt237: ~halts (TM_from_str "1RB0LE_0RC---_0LD1LE_1LD0LA_1RC1RF_0RB0RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt238: ~halts (TM_from_str "1RB0LE_0RC0RB_0LD1LE_1LD0LA_1LA1RF_1RC---") c0.
Proof. solve_cert (RWL_mod 1001 300000 300000 2 3200 1 5 4 0). Time Qed.

Lemma nonhalt239: ~halts (TM_from_str "1RB1LE_0RC---_0LD1RA_1RC1LD_0LF0RA_0RB0LE") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt240: ~halts (TM_from_str "1RB1RC_0RC0RF_0LD1RF_0LA1LE_1LD1LA_---0RB") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt241: ~halts (TM_from_str "1RB1LE_0RC1RD_1LA0RB_1RC0LE_---1LF_0LA0LF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt242: ~halts (TM_from_str "1RB0LE_0RC1RD_1LA0RB_1RC1LE_---1LF_0LA0LF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt243: ~halts (TM_from_str "1RB---_0RC1LD_1LA---_0LD0LE_0LA1RF_0RF0RB") c0.
Proof. solve_cert (CPS_LRU 1001 100000 100000 2 3200 1 14 1 0). Time Qed.

Lemma nonhalt244: ~halts (TM_from_str "1RB---_0RC1LD_1LA0RF_1LE0LD_0LA0LE_0RB1RF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt245: ~halts (TM_from_str "1RB0RF_0RC1LD_1LA1RC_1LE0LD_0LA---_0LE0RB") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt246: ~halts (TM_from_str "1RB0LA_0RC1LD_1LA0RF_0LE0LD_1RC---_0RB1LE") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt247: ~halts (TM_from_str "1RB1LE_0RC0RD_1LA0RB_1RC0LE_1LF---_0LA0LF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt248: ~halts (TM_from_str "1RB0LE_0RC0RD_1LA0RB_1RC1LE_1LF---_0LA0LF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt249: ~halts (TM_from_str "1RB0RA_0LC0RD_1LF1RD_1LE---_1RA0LF_0LE0RB") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt250: ~halts (TM_from_str "1RB0LA_0LC1RF_1LE1RD_0RB---_0LE1LA_0RF0RD") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt251: ~halts (TM_from_str "1RB0LA_0LC1RF_1LE1RD_0RB0RF_1LC1LA_---0RD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt252: ~halts (TM_from_str "1RB0LA_0LC1RF_0LE1RD_0RB0RD_0RF1LA_1LC---") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt253: ~halts (TM_from_str "1RB0LA_0LC1RF_1LC1RD_0RB0LE_0RF1LA_0RD---") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt254: ~halts (TM_from_str "1RB1LE_0LC1RF_0LA1RD_0RB0RF_1LC1LA_---0RD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt255: ~halts (TM_from_str "1RB0LD_0LC---_1LC1LD_1RE0LA_0RB1RF_0RE0RF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt256: ~halts (TM_from_str "1RB---_0LC1RF_1RA1LD_1LE0LD_0RB0LE_0RF0RA") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt257: ~halts (TM_from_str "1RB1RF_0LC0RA_1LC1LD_1LE0LD_1RA---_0RB0RF") c0.
Proof. solve_cert (RWL_mod 0 30000 30000 2 3200 2 1 4 0). Time Qed.

Lemma nonhalt258: ~halts (TM_from_str "1RB0LD_0LC1RF_---1LD_1LE0LE_1RA1LC_0RA0RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt259: ~halts (TM_from_str "1RB0LD_0LC1RF_1LC1LD_1LE0LA_1LA---_0RB0RF") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 2 4 2 0). Time Qed.

Lemma nonhalt260: ~halts (TM_from_str "1RB0LD_0LC1RF_1LC1LD_0RE0LA_---1LA_0RB0RF") c0.
Proof. solve_cert (RWL_mod 0 30000 30000 2 3200 2 1 4 0). Time Qed.

Lemma nonhalt261: ~halts (TM_from_str "1RB---_0LC1LE_1LC1LD_0LE0LD_1RF---_0RB0RF") c0.
Proof. solve_cert (CPS_LRU 1001 100000 100000 2 3200 1 14 1 0). Time Qed.

Lemma nonhalt262: ~halts (TM_from_str "1RB---_0LC1LE_1LC1LD_0LE0LD_1LA1RF_0RB0RF") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 1 3 2 0). Time Qed.

Lemma nonhalt263: ~halts (TM_from_str "1RB---_0LC0RB_1RE1LD_1LC0LF_1RA0RE_0RA0LD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt264: ~halts (TM_from_str "1RB0LA_0LC1RE_1LA1LD_1LC1RF_0RB0RF_---0RE") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt265: ~halts (TM_from_str "1RB1RE_0LC0RB_0RA1LD_1LC0LF_1RA1LF_---0LD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt266: ~halts (TM_from_str "1RB0RE_0LC0RB_0RA1LD_1LC0LF_1RA1LF_0LD---") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt267: ~halts (TM_from_str "1RB---_0LC1RE_1LC1LD_1LA1LF_0RB0RE_0LA0LF") c0.
Proof. solve_cert (CPS_LRU 1001 100000 100000 2 3200 1 14 1 0). Time Qed.

Lemma nonhalt268: ~halts (TM_from_str "1RB---_0LC1RE_1LC1LD_1LA0RF_0RB0RE_---0LA") c0.
Proof. solve_cert (RWL_mod 0 30000 30000 2 3200 2 1 4 0). Time Qed.

Lemma nonhalt269: ~halts (TM_from_str "1RB1RF_0LC1RE_1LC1LD_1LA0LA_0RB0RE_0LD---") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 2 6 2 0). Time Qed.

Lemma nonhalt270: ~halts (TM_from_str "1RB---_0LC0RE_1LC1LD_1LA1RF_---0LA_0RB0RF") c0.
Proof. solve_cert (CPS_LRU 1001 100000 100000 2 3200 1 14 1 0). Time Qed.

Lemma nonhalt271: ~halts (TM_from_str "1RB0LA_0LC0RE_1LC0LD_1RE1LA_1RF---_0RB0RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt272: ~halts (TM_from_str "1RB1RF_0LC---_1LC0LD_1RE0LA_0RF0RE_0RB1LD") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt273: ~halts (TM_from_str "1RB---_0LC1LF_1LC0LD_1RE0LF_0RB0RE_1LD1RA") c0.
Proof. solve_cert (RWL_mod 1001 300000 300000 2 3200 1 5 4 0). Time Qed.

Lemma nonhalt274: ~halts (TM_from_str "1RB1RF_0LC1LA_1LC0LD_1RE0LA_0RB---_0RE0RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt275: ~halts (TM_from_str "1RB0RA_0LC0LF_---0LD_1RE1LC_1RA1LF_---1LD") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt276: ~halts (TM_from_str "1RB0LA_0LC1RE_1LA0LD_1LC1RF_0RB0RF_0RE---") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt277: ~halts (TM_from_str "1RB0RF_0LC1RF_1RA0LD_0RB1LE_1LC1LD_---0RA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt278: ~halts (TM_from_str "1RB0LA_0LC1RE_1LC0LD_1LA0RE_1RF---_0RB0RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt279: ~halts (TM_from_str "1RB0LA_0LC0RE_1LC0LD_1LA1RE_1RF---_0RB0RF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt280: ~halts (TM_from_str "1RB---_0LC0RD_1RD1LC_1RA1LE_0RB0LF_0LE0RA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt281: ~halts (TM_from_str "1RB1RA_0LC---_1LD1LC_1LE0RA_1RF0LD_0LE0RF") c0.
Proof. solve_cert (RWL_mod 0 30000 30000 2 3200 2 1 4 0). Time Qed.

Lemma nonhalt282: ~halts (TM_from_str "1RB0RE_0LC---_1LD1LC_1RA0LF_0RA1RE_0LD0RB") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt283: ~halts (TM_from_str "1RB---_0LC0RB_0RD1LC_1RA1LE_1RD0LF_0LE0RA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt284: ~halts (TM_from_str "1RB---_0LC1RD_0RD1LC_0RA0LE_1RA0LF_0RB1LF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt285: ~halts (TM_from_str "1RB0LA_0LC1RE_0LD1LC_0RE1LA_1RF---_0RB0RF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt286: ~halts (TM_from_str "1RB---_0LC0RF_0LD1LC_0LE0RA_1RF0RB_1RA1LE") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt287: ~halts (TM_from_str "1RB---_0LC1LE_0LD1LC_0LE0RA_1RF0RB_1RA0RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt288: ~halts (TM_from_str "1RB---_0LC1LE_0LD1LC_1RA0LE_0RB0RF_0RA1RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt289: ~halts (TM_from_str "1RB0RE_0LC1RA_0LD1LC_0RA1LD_0LF1RE_---0RB") c0.
Proof. solve_cert (RWL_mod 1001 1000000 1000000 1 3200 2 2 4 0). Time Qed.

Lemma nonhalt290: ~halts (TM_from_str "1RB---_0LC1LD_0RB1LC_0LE0RF_1RA0LD_0RA1RF") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt291: ~halts (TM_from_str "1RB---_0LC0RD_0RB1LC_1RA0LE_0LF0RA_1RD1LF") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt292: ~halts (TM_from_str "1RB0LF_0LC0RD_1LA1LC_1RE1RD_0RB---_0LA0RE") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt293: ~halts (TM_from_str "1RB0LF_0LC1RD_1LC1LA_0RE0RD_0RB---_1RE0LA") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt294: ~halts (TM_from_str "1RB0LF_0LC1RD_1LC1LA_0RE0RD_0RB---_0LA1RE") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt295: ~halts (TM_from_str "1RB1RE_0LC1RD_---1LA_0RE0RD_0LA0LF_1LF1LC") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

Lemma nonhalt296: ~halts (TM_from_str "1RB0LA_0LC1RD_1LE1LA_0RB0RF_1LC1RF_---0RD") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt297: ~halts (TM_from_str "1RB0LA_0LC1RD_0LE1LA_0RB0RF_1LC1RF_0RD---") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt298: ~halts (TM_from_str "1RB1LE_0LC1RD_1LC1LA_0RB0RD_0LA0LF_---0LE") c0.
Proof. solve_cert (RWL_mod 1001 100000 100000 1 3200 2 6 2 0). Time Qed.

Lemma nonhalt299: ~halts (TM_from_str "1RB0LC_0LA0RB_1RD1RF_1LE0RD_1LA1LC_---0LE") c0.
Proof. solve_cert (NG 0 30000 30000 3 2 4 0 true). Time Qed.

Lemma nonhalt300: ~halts (TM_from_str "1RB0LC_0LA0RB_1LA1RD_0RE0RD_0LF---_1LF1LC") c0.
Proof. solve_cert (RWL_mod 0 30000 30000 2 3200 2 1 4 0). Time Qed.

Lemma nonhalt301: ~halts (TM_from_str "1RB0LC_0LA0RB_1LA0RD_1RE1RD_0LF---_1LC1LF") c0.
Proof. solve_cert (RWL_mod 0 30000 30000 2 3200 2 1 4 0). Time Qed.

Lemma nonhalt302: ~halts (TM_from_str "1RB1LA_0LA1RC_0RB1RD_0LE0RD_0LF---_1LF0RC") c0.
Proof. solve_cert (RWL_mod 0 30000 30000 2 3200 2 1 4 0). Time Qed.

Lemma nonhalt303: ~halts (TM_from_str "1RB1LA_0LA1RC_0RB0RD_0LE1RD_---0LF_0RC1LF") c0.
Proof. solve_cert (RWL_mod 0 30000 30000 2 3200 2 1 4 0). Time Qed.

Lemma nonhalt304: ~halts (TM_from_str "1RB1LA_0LA1LC_1RE0LD_0LC0RF_1RF0RE_0RB---") c0.
Proof. solve_cert (NG 0 100000 100000 2 4 0 0 true). Time Qed.

